# Generated by Django 2.0.6 on 2018-07-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('email', models.EmailField(default='d@d.com', max_length=255)),
                ('password', models.CharField(default='password', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('gender', models.CharField(default='Flying Fuck', max_length=15)),
                ('phone1', models.IntegerField(default=0)),
                ('phone2', models.IntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('password', models.CharField(default='password', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(default='Hogwarts')),
                ('pin_code', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('card_id', models.CharField(default=None, max_length=255, null=True)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(auto_now=True)),
                ('company_to_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
            ],
        ),
    ]
