# Generated by Django 2.0.6 on 2018-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='meet_time',
            field=models.DateTimeField(default=None),
        ),
    ]
