# Generated by Django 2.0.6 on 2018-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_visitor_is_inside_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='is_inside_building',
            field=models.BooleanField(default=True),
        ),
    ]
