# Generated by Django 2.0.6 on 2018-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_remove_visitor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='meet_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
