# Generated by Django 2.0.6 on 2018-07-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_auto_20180702_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone1',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone2',
            field=models.CharField(default=None, max_length=14),
        ),
    ]
