# Generated by Django 2.0.6 on 2018-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_auto_20180702_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_image/'),
        ),
    ]
