# Generated by Django 2.0.6 on 2018-07-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_auto_20180703_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
