# Generated by Django 2.0.6 on 2018-07-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
