# Generated by Django 2.0.6 on 2018-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NA', max_length=255)),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('email', models.EmailField(default='d@d.com', max_length=255)),
                ('password', models.CharField(default='password', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
